Automated rollback of commit 482d2be27abd4e54b628cfdb5aacb29a1311a6c6 (and changelist 539090160).
*** Reason for rollback ***

Causes cc_library targets depending on cc_grpc_library targets to fail to build with

> error: no member named 'grpc' in namespace [...]

*** Original change description ***

Compute the value of plugin_output from proto_info

Additional information is needed whether protoc generates a single file or multiple files.

Add output_files to proto_lang_toolchain (enum "single","multiple") and propagate it through ProtoLangToolchainInfo.

Add experimental_output_files to proto_common.compile, that can override the value, for faster migration path.

When the value is set, automatically compute plugin_output.

When the (legacy) plugin_output is not set to a file, set it auto...

***

PiperOrigin-RevId: 539114947
Change-Id: Iea4c852e72b07abd7b1fb80567b0cbca94736b1a